### ISSUE TITLE
No implicit conversion of String into Integer (TypeError) when converting orders

### ISSUE THREAD

**Issue by michaelwolz** [Shopify/shopify_transporter#124]
![screenshot 2018-11-19 16 04 16](https://user-images.githubusercontent.com/7479806/48715260-e331e880-ec14-11e8-94ec-32ad1ce46091.png)

**Comment by khoimm92** [comment]
Hi there, i also face this problem. Any update?

**Comment by surajreddy** [comment]
Hi folks, sorry for the delay in taking a look at this! 

It seems to be a problem with extracting discounts from the order.

Does the conversion complete if you remove the discount stage step in your configuration file and change it to this?

```
  order:
    record_key: increment_id
    pipeline_stages:
      - TopLevelAttributes
      - LineItems
      - AddressesAttribute
      - Transactions
      - ShippingLines
```

(Removed `- Discounts`)
